giantswarm/cluster-api-provider-aws

- .circleci/config.yml
- Makefile
This PR changes the circle CI config to use the git tag name as docker image tag when building.
Based on https://github.com/giantswarm/cluster-api-provider-azure/pull/13
> push images on tag

- .circleci/config.yml
Towards https://github.com/giantswarm/roadmap/issues/1832
Follow-up for https://github.com/giantswarm/cluster-api-provider-aws/pull/411 which didn't have working image push for tags. Tested manually by exporting `CIRCLE_TAG`, so I'm confident this will work once this PR is merged. I can then push a Git tag so we can mark a specific commit on the `main` branch to use as our image (until upstream includes our fixes in a full-fledged release).
> Fix image push for tags

- api/v1beta2/network_types.go
- cmd/clusterawsadm/converters/cloudformation.go
- config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
- controllers/awscluster_controller_test.go
- pkg/cloud/converters/tags.go
- pkg/cloud/services/autoscaling/autoscalinggroup.go
- pkg/cloud/services/ec2/launchtemplate.go
- pkg/cloud/services/eks/iam/iam.go
- pkg/cloud/services/elb/loadbalancer.go
- pkg/cloud/services/network/natgateways.go
- pkg/cloud/services/network/routetables.go
- pkg/cloud/services/network/subnets.go
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/multi-az/kustomization.yaml
- test/e2e/data/infrastructure-aws/kustomize_sources/multi-az/patches/multi-az.yaml
- test/e2e/shared/defaults.go
- test/e2e/suites/unmanaged/helpers_test.go
- test/e2e/suites/unmanaged/unmanaged_functional_test.go
Towards https://github.com/giantswarm/roadmap/issues/1932 and https://github.com/giantswarm/roadmap/issues/1832
We decided that we want to revert the buggy upstream change. I did that in separate commits, so it should be easy to see where the changes come from. On top, I added a unit test which covers all AWS API calls throughout full reconciliation of a `AWSCluster` with managed VPC and subnets. My suggestion for reviewers is to look at commits oldest-to-newest. Note how my unit test found a few issues such as not writing latest information back to memory – those points are fixed and reconciliation should now run smoother, in one run.
After the workaround, we will invest time into the larger upstream issue https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4026 where a …
> Workaround to get managed subnets working again

- .circleci/config.yml
- .github/workflows/release.yml
- README.md
https://github.com/giantswarm/roadmap/issues/2561
We want to adapt this CAPA repo fork in the same way as we did for CAPI (https://github.com/giantswarm/cluster-api). The only difference is that CAPA doesn't provide a GitHub workflow to create releases, so I added one myself, now totaling to 3 files of difference between our repo and upstream (see hints in README).
The CircleCI config and README were taken from our `main` branch and improved, so it's clear how developers can use this repo.
This PR merges into `release-2.2`, and afterwards I'll ensure that `main`/`release-2.2` are aligned.
Extracting the manifest from autogenerated GitHub releases works fine and a `cluster-api-provider-aws-app` PR will follow after we're done here.
> Adapt release-2.2 branch in our fork to build images and create GitHub releases from tags, update development instructions

- .github/workflows/release.yml
Upstream had changed their Makefile targets for release notes and related tooling.
> Adapt GitHub release workflow to upstream Makefile changes

- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
- pkg/cloud/services/s3/s3.go
- pkg/cloud/services/s3/s3_test.go
Towards https://github.com/giantswarm/roadmap/issues/2929
Cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4518 into our `release-2.2` fork branch.
Note that [`giantswarm-aws-account-prerequisites` already has this permission](https://github.com/giantswarm/giantswarm-aws-account-prerequisites/blob/master/capa-controller-role/capa-controller-policy.json) added (recently), so I won't open a related PR on that repo.
> Tag S3 bucket as owned by cluster

- pkg/cloud/services/s3/s3.go
- pkg/cloud/services/s3/s3_test.go
Cherry-pick https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4625 into our fork's `release-2.2` branch so we can immediately use it for https://github.com/giantswarm/roadmap/issues/2929.
> Use `AdditionalTags` for S3 buckets

- exp/controllers/awsmachinepool_controller.go
- exp/controllers/awsmachinepool_controller_test.go
- pkg/cloud/scope/machinepool.go
- pkg/cloud/services/autoscaling/autoscalinggroup.go
- pkg/cloud/services/autoscaling/autoscalinggroup_test.go
- pkg/cloud/services/eks/nodegroup.go
Towards https://github.com/giantswarm/giantswarm/issues/29030
Cherry-picked https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/4d33ed1ebe695f9eb4a2578d429c2afe7d48c968 from @calvix
> Update ASG - do not set desired value for machinepool which have externally managed replicas

- pkg/cloud/services/awsnode/cni.go
towards https://github.com/giantswarm/roadmap/issues/3105
for now always just delete the aws-node  
I want to merge this fix to allow another team to easily try debug the cillium issue.
> :bug: EKS - when aws-cni is disabled deleted all resources including helm managed resources

- api/v1beta2/network_types.go
- pkg/cloud/scope/shared.go
Not really sure about the naming. I suppose `Primary` doesn't really tell you what these subnets are, but then again neither does `secondary`. I suppose the best way to name it is `FilterNonCNI`, but that may be a bit too descriptive.
> Filter CNI subnets when creating EKS NodeGroup

- hack/tools/go.sum
- pkg/cloud/identity/identity.go
- pkg/cloud/identity/identity_test.go
- pkg/cloud/scope/session.go
towards https://github.com/giantswarm/roadmap/issues/3254
if this makes sense to you I will make a PR upstream 
test in china `galaxy` and on `golem` work as expected
> :bug: Create a `aws.Config` with region to be able to work different AWS partition (like gov cloud or china AWS partition)

- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
- exp/api/v1beta1/conversion.go
- exp/api/v1beta1/zz_generated.conversion.go
- exp/api/v1beta2/types.go
- exp/api/v1beta2/zz_generated.deepcopy.go
- pkg/cloud/scope/launchtemplate.go
- pkg/cloud/services/ec2/launchtemplate.go
Towards https://github.com/giantswarm/giantswarm/issues/27903
> ✨ Add non root volumes to AWSMachineTemplate

- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
- pkg/cloud/services/s3/s3.go
Towards https://github.com/giantswarm/roadmap/issues/3442, fix for #592
> Delete machine pool user data files that did not get deleted yet by the lifecycle policy

- .circleci/config.yml
- go.mod
- pkg/cloud/services/s3/s3_test.go
For some reason, CI went through in #593 and therefore the test failure wasn't detected. @fiunchinho found this fix missing in `release-2.4` as well (see https://github.com/giantswarm/cluster-api-provider-aws/pull/595/files).
> S3 test fixes

- pkg/cloud/services/s3/s3.go
- pkg/cloud/services/s3/s3_test.go
Towards https://github.com/giantswarm/roadmap/issues/3442
To be merged after https://github.com/giantswarm/cluster-api-provider-aws/pull/596 (stacked PR).
This adds the suggested changes as requested in the review of https://github.com/giantswarm/cluster-api-provider-aws/pull/593.
> Use feature gate for S3 storage

- config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
- exp/api/v1beta2/zz_generated.deepcopy.go
I forgot to run `make generate` because I'm stupid.
> Update generated files

- exp/controllers/awsmachinepool_controller_test.go
- pkg/cloud/services/ec2/launchtemplate.go
Same as #602, ported to `release-2.4` branch
> Fix subtests running in same environment and reconciliation bug which was not covered because of that

- .circleci/config.yml
This makes the diff
```
git diff main..release-2.4 -- .circleci/ .github/workflows/release.yml README.md
```
empty again.
We should also update our `main` branch altogether, but that's another story.
> Use newer CircleCI config from `release-2.4` branch

- exp/controllers/awsmachinepool_controller_test.go
Seems I merged #601 where the test had failed. Probably because `make test` in CI was brand-new, or maybe we need to enforce a green build somehow.
> Fix S3 test

- api/v1beta2/tags.go
- exp/controllers/awsmachinepool_controller.go
- exp/controllers/awsmachinepool_controller_test.go
- exp/controllers/awsmanagedmachinepool_controller.go
- pkg/cloud/services/ec2/launchtemplate.go
- pkg/cloud/services/ec2/launchtemplate_test.go
- pkg/cloud/services/interfaces.go
- pkg/cloud/services/mock_services/ec2_interface_mock.go
- pkg/cloud/services/mock_services/objectstore_machine_interface_mock.go
- pkg/cloud/services/s3/s3.go
Port https://github.com/giantswarm/cluster-api-provider-aws/pull/601 and the test fix https://github.com/giantswarm/cluster-api-provider-aws/pull/605 to our `release-2.4` branch.
I first thought this would become more complex due to Ignition-related upstream changes, but the choice `IgnitionStorageTypeOptionClusterObjectStore`/`IgnitionStorageTypeOptionUnencryptedUserData` isn't supported yet for machine pools, so it looks like we can simply forward-port my changes as such.
For review, maybe it helps to compare this diff against the [original PR's diff](https://github.com/giantswarm/cluster-api-provider-aws/pull/601), since those should almost be equal.
> Try deleting machine pool user data file from S3 when pruning an old launch template version, add S3 storage tests (port to release-2.4)

- .github/workflows/release.yaml
Failed after https://github.com/giantswarm/cluster-api-provider-aws/pull/607 because the release tooling / Makefile changed.
Towards https://github.com/giantswarm/roadmap/issues/3170.
> Fix Giant Swarm fork release workflow

- pkg/cloud/tags/tags.go
- pkg/cloud/tags/tags_test.go
Towards https://github.com/giantswarm/giantswarm/issues/31488
Backporting https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5181
> 🐛 Filter out AWS internal tags when reconciling

- api/v1beta2/awsmachine_types.go
- api/v1beta2/awsmachine_webhook.go
- cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
- cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
- controllers/awsmachine_controller.go
- exp/api/v1beta2/awsmachinepool_webhook.go
- exp/controllers/awsmachinepool_controller.go
- exp/controllers/awsmachinepool_controller_test.go
- pkg/cloud/services/ec2/launchtemplate.go
- pkg/cloud/services/ec2/launchtemplate_test.go
- pkg/cloud/services/s3/s3.go
See changes made in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5172
I have yet to test these changes. Our fork's default must remain to use S3 even if nothing is explicitly specified (see comment and custom change to `DefaultMachinePoolIgnitionStorageType`). That's because cluster-aws didn't have it explicitly set before and the fix in https://github.com/giantswarm/cluster-aws/pull/981 only applies to new CAPA cluster releases.
Initial work was in https://github.com/giantswarm/roadmap/issues/3442 and https://github.com/giantswarm/cluster-api-provider-aws/pull/592 (et al).
> Adapt Ignition user data S3 support to upstream PR

- controllers/awsmachine_controller_unit_test.go
- pkg/cloud/services/ec2/instances.go
**What type of PR is this?**
/kind feature
**What this PR does / why we need it**:
We don't want CAPA managing the security groups of the ENIs created by other components, like `cilium`. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**Special notes for your reviewer**:
**Checklist**:
**Release note**:
```release-note
Only manage security groups for ENIs tagged by CAPA
```
> :sparkles: Only manage security groups for ENIs tagged by CAPA

- pkg/cloud/services/s3/s3.go
Towards https://github.com/giantswarm/giantswarm/issues/32640
> :sparkles: Add karpenter IAM Roles to the S3 bucket policy so that karpenter nodes can read userdata

- controllers/awsmachine_controller.go
PR upstream https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5462
> :bug: Wire logger into machine scope

- exp/controllers/awsmachinepool_controller.go
Backporting https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5333
> ✨ Avoid reconciling AWSMachinePools when only the status field has changed

- pkg/cloud/services/eks/oidc_test.go
- pkg/internal/testcert/testcert.go
Backport of this fix:
> This updates the oidc test to fix the cert thumbprints from the server as these change with every go version when using httptest.NewTLSServer.
We otherwise run into CI test failures.
> Fix oidc test failure

- controllers/awsmachine_controller.go
- controllers/awsmachine_controller_test.go
This fixes the error `invalid secret backend` because CAPA mistakenly tries to delete bootstrap data that won't ever exist for machine pool machines as their bootstrapping is done from another controller. See other places where `if !machineScope.IsMachinePoolMachine()` was already correctly used.
The fix is critical because currently, some clusters fail to continue deletion as the reconciliation logic is stopped at the mentioned error.
> Only try to delete AWSMachine bootstrap data for non-machine pool machines

- exp/api/v1beta2/awsmachinepool_types.go
- exp/controllers/awsmachinepool_controller.go
**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:
Fixes a race condition, where the `AWSMachinePool` object gets updated before the `MachinePool` and `KubeadmControlPlane` objects. Because of this, the controller takes the wrong decisions during reconciliation as the data is not consistent between objects. With this, the `awsmachinepool` controller will delay reconciliation if the GiantSwarm release labels don't match between the required objects.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/giantswarm/giantswarm/issues/34042
**Special notes for your reviewer**:
**Checklist**:
**Release note**:
```release-note
```
> :bug: Fix cluster upgrade version skew
